### ISSUE TITLE
[INFO] ESP32-DOIT + FTD2232H

### ISSUE THREAD

**Issue by mywalkb** [Matheus-Garbelini/braktooth_esp32_bluetooth_classic_attacks#1]
Hi @Matheus-Garbelini, for this project is it valid the same suggestion of this comment https://github.com/Matheus-Garbelini/esp32_bluetooth_classic_sniffer/issues/2#issuecomment-921671765 ?

**Comment by Matheus-Garbelini** [comment]
Hi @mywalkb 
Yes, the same suggestion applies. 

Thanks for your interest.
