### ISSUE TITLE
wdissector.tar.zst can't be decompressed

### ISSUE THREAD

**Issue by yangting111** [Matheus-Garbelini/braktooth_esp32_bluetooth_classic_attacks#10]
![1665131215002](https://user-images.githubusercontent.com/39514759/194508626-a39402e5-c993-48b9-a698-b9422f11e421.png)

**Comment by Matheus-Garbelini** [comment]
Hi @yangting111 have you installed zsyt first?
You can install it with: `sudo apt install zstd` before extracting the file

**Comment by yangting111** [comment]
Thank you for your reply！The result is shown as follows：
![1665131686790](https://user-images.githubusercontent.com/39514759/194510233-7840094b-8760-4cd7-86bb-6d1c1a9e68b5.png)

**Comment by Matheus-Garbelini** [comment]
Thanks @yangting111 
can you try with this instead: https://github.com/Matheus-Garbelini/braktooth_esp32_bluetooth_classic_attacks/releases/download/v1.0.1/release.zip

After download you can unzip it `unzip release.zip && cd release` then run again `tar -I zstd -xf wdissector.tar.zst`

**Comment by yangting111** [comment]
Thank you very much for helping me solve this problem.
