### ISSUE TITLE
error unpacking the archive wdissector.tar.zst

### ISSUE THREAD

**Issue by mr-slonn** [Matheus-Garbelini/braktooth_esp32_bluetooth_classic_attacks#12]
My linux knowledge is 0 :(
When executing point B of the instruction, I get an error, and I can't find a solution

┌──(kali㉿kali)-[~/braktooth_esp32_bluetooth_classic_attacks]
└─$ tar -I zstd -xf wdissector.tar.zst                                                      
zstd: /*stdin*\: unsupported format 
tar: Child returned status 1
tar: Error is not recoverable: exiting now

tar version:
tar (GNU tar) 1.34

zstd version:
*** zstd command line interface 64-bits v1.5.2, by Yann Collet ***

Kali version:
Distributor ID: Kali
Description:    Kali GNU/Linux Rolling
Release:        2022.3
Codename:       kali-rolling

**Comment by mr-slonn** [comment]
after much agony, it turned out that the file was not fully downloaded :( (although there were no errors when downloading) and therefore it was not unpacked.

**Comment by warlock2k** [comment]
I'm facing the same issue, how did you know that the file wasn't fully downloaded?

**Comment by mr-slonn** [comment]
somewhere on the Internet I saw a tip to the question "why does szdt not work?" the answer is "check if the file is damaged when downloading" and what was my surprise that it is 300 megabytes and not 140 kilobytes

**Comment by warlock2k** [comment]
@mr-slonn, makes sense. I downloaded the file directly from the releases and it works great now, thank you!
