### ISSUE TITLE
How to reduce the latency

### ISSUE THREAD

**Issue by yangte** [Matheus-Garbelini/braktooth_esp32_bluetooth_classic_attacks#14]
Hello ,guys ;

I am having some trouble using these ESP32 development boards, I find the UART latency is 1259us and wonder how to reduce the latency of this serial port?

[ESP32BT] Measuring UART Latency...
[ESP32BT] USB Latency:1259 us [OK]
Serial port /dev/ttyUSB1@4000000 opened

**Comment by Matheus-Garbelini** [comment]
Hi, what esp32 board are you using? 
Also are you running ubuntu under a VM or native machine?

**Comment by yangte** [comment]
Hi ， @Matheus-Garbelini 
Thanks for your reply .
I use vmware machine and use the ESP-WROVER-E kit , when I use the the vmware I found that my usb latency is 505us . 
I wonder if 505us is enough for these tests ?

**Comment by Matheus-Garbelini** [comment]
Hi @yangte.
Yes, 505us is enough. But make sure to allow maximum CPU cores for your vm. For example, a minimum of 4 CPUs is recommended. Using USB 3 (blue port) also helps with latency.

**Comment by yangte** [comment]
@Matheus-Garbelini 
Ok , Thanks a lot !

**Comment by ValdikSS** [comment]
@yangte @Matheus-Garbelini is the connection uses OHCI (USB 1.1) by any chance?
If yes, check https://lore.kernel.org/linux-usb/3fe845b9-1328-4b40-8b02-61a879bea6df@valdikss.org.ru/T/#u
The patch is in the latest message.
