### ISSUE TITLE
Source request form not working?

### ISSUE THREAD

**Issue by tcz** [Matheus-Garbelini/braktooth_esp32_bluetooth_classic_attacks#31]
I submitted the source request form twice with my academic email address but did not get a response for over a month.

Can you help with this?

**Comment by Matheus-Garbelini** [comment]
Hi @tcz can check again https://src.braktooth.com
Our form send emails automatically to valid university emails, but it got somewhat disabled due to permissions issues with google sheet Apps scrips.
