### ISSUE TITLE
The Usage of firmware.py is incorrect described in README.md

### ISSUE THREAD

**Issue by JianwenLi-GS** [Matheus-Garbelini/braktooth_esp32_bluetooth_classic_attacks#4]
2) Installation Instructions
python3 firmware.py /dev/ttyUSB3

should be `python3 firmware.py flash /dev/ttyUSB3`

```bash
$  python3 firmware.py /dev/ttyUSB3
------ Usage help -------
./firmware.py **flash** <port name>  # Flash firmware using serial port
./firmware.py reset <port name>  # Reset firmware using serial port
```

**Comment by Matheus-Garbelini** [comment]
@JianwenLi-GS thanks.
Just fixed this on last commit

**Comment by JianwenLi-GS** [comment]
> @JianwenLi-GS thanks. Just fixed this on last commit

"python3 flash firmware.py" on last commit?  the correct is "python3 firmware.py flash"

**Comment by Matheus-Garbelini** [comment]
@JianwenLi-GS 
Yes, I've fixed the typo, thanks.
