### ISSUE TITLE
 Please help, why could not open /dev/ttyusb3@115200 appear?

### ISSUE THREAD

**Issue by m1cc0s0ft** [Matheus-Garbelini/braktooth_esp32_bluetooth_classic_attacks#42]
Hello, I am using the system ubuntu22.04, and burned the firmware version 1.4 into the esp. During the test exp process, it keeps appearing.

monitor error:could not open /dev/ttyusb3@115200

loop detected: could 1.restating session........
core dumped

**Comment by mrmischi3f** [comment]
Hi, facing the same problem here. Did you manage to fix it?

**Comment by m1cc0s0ft** [comment]
> Hi, facing the same problem here. Did you manage to fix it?

Hi, I changed to ubuntu18 version and it solved, hope you can too

**Comment by m1cc0s0ft** [comment]
good
